### ISSUE TITLE
Request to add setting for selective fetchpriority assignment

### ISSUE THREAD

**Issue by rc-advertoo** [erikyo/f2ll#9]
Hello,
In your locator.ts, your code adds fetchpriority to the images that are in the initial viewport. There are certain cases where it is preferable to selectively define the images to which you assign fetchpriority.

Could I suggest adding a setting to enable/disable this feature?

This is the code I am referring to:

	if (isElement.nodeName === "IMG") {
		isElement.setAttribute("fetchpriority", "high");
		isElement.setAttribute("decoding", "async");

		const linkHeader = document.createElement("link");
		linkHeader.setAttribute("rel", "preload");
		linkHeader.setAttribute("as", "image");
		linkHeader.setAttribute(
			"href",
			(isElement as HTMLImageElement).src as string,
		);
		linkHeader.setAttribute("fetchpriority", "high");

		document.head.appendChild(linkHeader);
	}

Thanks

**Comment by erikyo** [comment]
OK, that seems reasonable.

- Regarding where to store the option, what do you think about adding it to the [window object](https://github.com/erikyo/auto-lazyload?tab=readme-ov-file#example)? For example, we could name the option `fetchprioritySupport` and set its default value to true.
- As for the code you highlighted, I suggest creating a utility function that takes the URL as a parameter and automatically adds it to the header if required by the user.

**Comment by rc-advertoo** [comment]
Yes, both are good ideas!
Regarding fetchprioritySupport, I think it is better to add a prefix to avoid being overridden by other scripts.
For example: window.lazyLoadFetchprioritySupport. I know it is long, but it is just an example :)

**Comment by erikyo** [comment]
OK I will do that!

ps. about the option it's already [like what you suggest](https://github.com/erikyo/auto-lazyload?tab=readme-ov-file#example), and the autolazy options are stored under `window.autolazy`. So, in order to disable the fetch support will be sufficient to state:
`window.autolazy.fetchprioritySupport = false`
before loading the script. 

Sounds good?

**Comment by rc-advertoo** [comment]
It sounds great! 

P.S. The other user 'rcwd' is also me. I forgot to switch accounts; this is my company profile, while 'rcwd' is my private profile

**Comment by erikyo** [comment]
sorry for the long wait and thanks for the suggestion! I just released v1.1.4 🚀
